case_column_name: case:concept:name
activity_column_name: concept:name
timestamp_column_name: time:timestamp
resource_column_name: org:resource
lifecycle_column_name: lifecycle:transition
data_model: Automatic Conformance Checking Model
data_pool: Automatic Conformance Checking Pool
data_job:  Automatic Conformance Checking Job
celonis:
  { base_url : https://academic-mengru-ji-rwth-aachen-de.eu-2.celonis.cloud,
    api_token : Zjg2N2I3NjQtMDJhNy00ZTlhLTlhZTEtYjk0YTZhNTI4MWM1OjUxeGlXTWxjSW41KzVUOVhHcDJPNm9wdU82YmdrMjEzRlRWanEzWGMwWUh5
}
