case_column: case:concept:name
activity_column: concept:name
timestamp_column: time:timestamp
resource_column: org:resource
data_model: Automatic Conformance Checking Model
data_pool: Automatic Conformance Checking Pool
data_job:  Automatic Conformance Checking Job
celonis:
  { base_url : https://academic-mengru-ji-rwth-aachen-de.eu-2.celonis.cloud,
    api_token : Zjg2N2I3NjQtMDJhNy00ZTlhLTlhZTEtYjk0YTZhNTI4MWM1OjUxeGlXTWxjSW41KzVUOVhHcDJPNm9wdU82YmdrMjEzRlRWanEzWGMwWUh5
}
