version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/Group4-Automatic-Conformance-Checking-insights-in-Celonis
    environment:
      FLASK_ENV: development
